from backend.models import (
    Base,
    User,
    Inbound,
    ClientStats,
    SystemSetting,
    UserSession,
    Outbound,
    RoutingRule,
    Node,
    NodeJoinCode,
    SharedCache,
)

from backend.database.connection import (
    database_url,
    engine,
    session_factory,
    Session,
    db_session,
    get_db_connection,
)
from backend.database.seeding import init_db

from backend.database.crud.auth import (
    hash_password,
    verify_password,
    authenticate_admin,
    update_admin_password,
    update_admin_credentials,
)

from backend.database.crud.inbounds import (
    inbound_to_dict,
    get_all_inbounds,
    get_inbound_by_id,
    add_inbound,
    update_inbound,
    delete_inbound,
    update_inbound_traffic,
)

from backend.database.crud.clients import (
    client_to_dict,
    get_clients_for_inbound,
    get_client_by_email,
    get_client_by_id_or_pwd,
    add_client_db,
    update_client_db,
    block_client_db,
    unblock_client_db,
    delete_client_db,
    update_client_traffic,
    update_client_traffic_by_email,
    reset_client_traffic_db,
    reset_all_client_traffics_for_inbound_db,
    reset_client_traffic_globally_db,
    reset_all_traffics_db,
)

from backend.database.crud.settings import (
    get_setting,
    set_setting,
    invalidate_settings_cache,
)

from backend.database.crud.sessions import (
    add_session_db,
    get_session_db,
    get_all_sessions_db,
    delete_session_db,
    clean_expired_sessions_db,
    update_session_ip_db,
)

from backend.database.crud.outbounds import (
    outbound_to_dict,
    get_all_outbounds,
    get_outbound_by_id,
    add_outbound,
    update_outbound,
    delete_outbound,
    update_outbound_traffic,
)

from backend.database.crud.routing import (
    routing_rule_to_dict,
    get_all_routing_rules,
    get_routing_rule_by_id,
    add_routing_rule,
    update_routing_rule,
    delete_routing_rule,
    update_rules_priority,
    sync_quick_security_rules,
    get_quick_security_rules_state,
)

from backend.database.crud.shared_cache import (
    get_shared_cache,
    set_shared_cache,
    delete_shared_cache,
    clean_expired_shared_cache,
    atomic_increment_shared_cache,
    get_int_shared_cache,
)

__all__ = [
    "Base",
    "User",
    "Inbound",
    "ClientStats",
    "SystemSetting",
    "UserSession",
    "Outbound",
    "RoutingRule",
    "Node",
    "NodeJoinCode",
    "database_url",
    "engine",
    "session_factory",
    "Session",
    "db_session",
    "get_db_connection",
    "init_db",
    "hash_password",
    "verify_password",
    "authenticate_admin",
    "update_admin_password",
    "update_admin_credentials",
    "inbound_to_dict",
    "get_all_inbounds",
    "get_inbound_by_id",
    "add_inbound",
    "update_inbound",
    "delete_inbound",
    "update_inbound_traffic",
    "client_to_dict",
    "get_clients_for_inbound",
    "get_client_by_email",
    "get_client_by_id_or_pwd",
    "add_client_db",
    "update_client_db",
    "block_client_db",
    "unblock_client_db",
    "delete_client_db",
    "update_client_traffic",
    "update_client_traffic_by_email",
    "get_setting",
    "set_setting",
    "invalidate_settings_cache",
    "add_session_db",
    "get_session_db",
    "get_all_sessions_db",
    "delete_session_db",
    "clean_expired_sessions_db",
    "update_session_ip_db",
    "outbound_to_dict",
    "get_all_outbounds",
    "get_outbound_by_id",
    "add_outbound",
    "update_outbound",
    "delete_outbound",
    "update_outbound_traffic",
    "routing_rule_to_dict",
    "get_all_routing_rules",
    "get_routing_rule_by_id",
    "add_routing_rule",
    "update_routing_rule",
    "delete_routing_rule",
    "update_rules_priority",
    "get_shared_cache",
    "set_shared_cache",
    "delete_shared_cache",
    "clean_expired_shared_cache",
    "atomic_increment_shared_cache",
    "get_int_shared_cache",
]
