"""Common utilities, logging, ANSI colors, process execution, and system checks."""

from __future__ import annotations

import os
import platform
import re
import shutil
import signal
import socket
import subprocess
import sys
from typing import Dict, List, Optional, Union

# ANSI Colors
RESET = "\033[0m"
BOLD = "\033[1m"
DIM = "\033[2m"
RED = "\033[0;31m"
GREEN = "\033[0;32m"
YELLOW = "\033[1;33m"
BLUE = "\033[0;34m"
CYAN = "\033[0;36m"
MAGENTA = "\033[0;35m"


def log_info(msg: str) -> None:
    print(f"{BLUE}[+]{RESET} {msg}", flush=True)


def log_success(msg: str) -> None:
    print(f"{GREEN}[✓]{RESET} {msg}", flush=True)


def log_warn(msg: str) -> None:
    print(f"{YELLOW}[!]{RESET} {msg}", flush=True)


def log_error(msg: str) -> None:
    print(f"{RED}[✗]{RESET} {msg}", flush=True)


def log_banner(title: str) -> None:
    line = "=" * 60
    print(f"\n{CYAN}{line}{RESET}")
    print(f"{BOLD}{title}{RESET}")
    print(f"{CYAN}{line}{RESET}\n", flush=True)


def check_root() -> None:
    """Verifies that the script is executed with root/administrator privileges on POSIX systems."""
    if platform.system() != "Windows":
        if os.geteuid() != 0:
            log_error("Для обновления панели требуются права root (sudo).")
            print(f"{YELLOW}Пожалуйста, запустите: sudo ./update.sh{RESET}\n")
            sys.exit(1)


def free_port(port: int) -> None:
    """Kills any stale process binding to the specified TCP port."""
    if platform.system() == "Windows":
        return

    # Check via lsof or fuser
    try:
        if shutil.which("fuser"):
            subprocess.run(["fuser", "-k", f"{port}/tcp"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        elif shutil.which("lsof"):
            out = subprocess.check_output(["lsof", "-t", f"-i:{port}"], stderr=subprocess.DEVNULL).decode().strip()
            for pid_str in out.split():
                if pid_str.isdigit():
                    try:
                        os.kill(int(pid_str), signal.SIGKILL)
                    except Exception:
                        pass
    except Exception:
        pass


def run_command(
    cmd: Union[List[str], str],
    cwd: Optional[str] = None,
    env: Optional[Dict[str, str]] = None,
    check: bool = True,
    capture: bool = False,
    timeout: Optional[float] = None,
) -> subprocess.CompletedProcess:
    """Executes a system shell command with proper stream handling."""
    shell = isinstance(cmd, str)
    full_env = os.environ.copy()
    if env:
        full_env.update(env)

    if capture:
        proc = subprocess.run(
            cmd,
            shell=shell,
            cwd=cwd,
            env=full_env,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            timeout=timeout,
        )
    else:
        proc = subprocess.run(
            cmd,
            shell=shell,
            cwd=cwd,
            env=full_env,
            timeout=timeout,
        )

    if check and proc.returncode != 0:
        err_msg = proc.stderr if capture else f"Exit code: {proc.returncode}"
        raise subprocess.CalledProcessError(proc.returncode, cmd, output=proc.stdout if capture else None, stderr=err_msg)

    return proc


def ensure_unencrypted_dns() -> None:
    """Ensures standard unencrypted UDP:53 DNS (8.8.8.8, 1.1.1.1) is available on the system."""
    if platform.system() == "Windows":
        return

    # Test basic UDP 53 resolution
    def test_dns_udp(server: str = "8.8.8.8", domain: str = "github.com") -> bool:
        packet = b"\xaa\xbb\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00"
        for part in domain.split("."):
            packet += bytes([len(part)]) + part.encode("ascii")
        packet += b"\x00\x00\x01\x00\x01"
        try:
            sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            sock.settimeout(2.0)
            sock.sendto(packet, (server, 53))
            data, _ = sock.recvfrom(1024)
            sock.close()
            return len(data) > 12
        except Exception:
            return False

    if test_dns_udp("8.8.8.8") or test_dns_udp("1.1.1.1"):
        return

    log_warn("Обнаружена проблема с DNS. Настройка надежных публичных DNS (8.8.8.8, 1.1.1.1)...")
    resolv_conf = "/etc/resolv.conf"
    if os.path.exists(resolv_conf) and not os.path.islink(resolv_conf):
        try:
            with open(resolv_conf, "w", encoding="utf-8") as f:
                f.write("# Generated by Sentinel Panel Updater\nnameserver 8.8.8.8\nnameserver 1.1.1.1\nnameserver 8.8.4.4\n")
            log_success("Установлены DNS-серверы: 8.8.8.8, 1.1.1.1 (UDP:53)")
        except Exception as e:
            log_warn(f"Не удалось обновить /etc/resolv.conf: {e}")
